" Initialize
" ------------------------------------------------------------
  set nocompatible

  " Initialize Pathogen
  runtime ~/.vim/autoload/pathogen.vim
  call pathogen#infect()
  call pathogen#helptags()

  filetype indent on
  filetype plugin on

" Modelines
set modeline
set modelines=3

" Things that help me revert
" ------------------------------------------------------------
  " But No swap files, those are annoying
  set noswapfile
  set nobackup
  set nowb

  " Persistent Undo
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile


  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  " let Vundle manage Vundle
  " required!

  Bundle 'gmarik/vundle'
  Bundle 'petdance/ack2'
  Bundle 'mattn/emmet-vim'
  Bundle 'scrooloose/nerdcommenter'
  Bundle 'scrooloose/nerdtree'
  Bundle 'Lokaltog/powerline'
  Bundle 'tpope/vim-fugitive'
  Bundle 'airblade/vim-gitgutter'
  Bundle 'tpop/vim-surround'
  Bundle 'Shougo/unite'

" Core mappings
" ------------------------------------------------------------

  let mapleader=" "
  imap jk <Esc>

" Powerline runtimepath append stuff that i feel belongs to the plugin folder
" but can't get working when it's there (TODO: get it working under plugins)
" -----------------------------------------------------------
  set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

" Kawaii stuff
" ------------------------------------------------------------
  " Show line numbers
  set nu

 " Font size
 set guifont=Inconsolata\ for\ Powerline:h14

 " Use 256 colors plz
 set t_Co=256

 " Split character (Default is '|'), yeah there's a trailing whitespace.
 set fillchars+=vert:\

  " Syntax highlighting and ColorSchemes
  syntax on
  set background=dark
  " colorscheme solarized

  " Treat '-' and '_' as word terminators
  set iskeyword-=_
  set iskeyword-=-

" Remaps
" ------------------------------------------------------------

  " Tabs
  nnoremap th :tabnext<CR>
  nnoremap tl :tabprev<CR>
  nnoremap tn :tabnew<CR>

  " Nerdtree
  nnoremap <C-S-n> :NERDTreeToggle<CR>

  " Format fixing remaps
    " Remove whitespace
    nnoremap <Leader>w :%s/\s\+$//e<CR>

" Mouse (LOL!) things
" ------------------------------------------------------------

  " Scrolling
  set mouse=a
  map <ScrollWheelUp> <C-Y>
  map <ScrollWheelDown> <C-E>

" Ignore Syntastic warnings on angular directives.
  let g:syntastic_html_tidy_ignore_errors=[" proprietary attribute \"ng-"]

" Do not deselect after nudging a block
  vnoremap < <gv
  vnoremap > >gv

" Unite mappings
" ------------------------------------------------------------

" Use file_rec/async
nnoremap <leader>t :Unite file_rec/async<cr>
" Fuzzy finder
call unite#filters#matcher_default#use(['matcher_fuzzy'])
